/*

 MAP4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 50 x 50
   Tile set      : C:\Users\Lenovo\Documents\GIT\Ancient_Dungeon\res\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map4Width 50
#define map4Height 50
#define map4Bank 0

extern unsigned char map4[];

/* End of MAP4.H */
