/*

 MENU.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define menuWidth 20
#define menuHeight 18
#define menuBank 0

extern unsigned char menu[];

/* End of MENU.H */
